### ISSUE TITLE
Snap failing to build 4/6 archs

### ISSUE THREAD

**Issue by JackDandy** [JackDandy/SickGear#15]
Hi @Lukewh 

For the last 24 hours, SnapCraft is showing refusal to build 4 of the 6 archs for SickGear. There are no changes to the SickGear build files. Do you have any idea what is wrong? Cheers.

<img src="https://i.vgy.me/wDSbwQ.png">

**Comment by Lukewh** [comment]
Hi @JackDandy, I no longer work at Canonical or on snapcraft.io. Pinging @tbille as he's the snapcraft.io lead now

**Comment by JackDandy** [comment]
Thanks @Lukewh appreciate all the help you gave when you were there, all the best for your future endeavors :)

And so, the changing of the guard, greetings @tbille - can you help me with the post above?

**Comment by tbille** [comment]
hey @JackDandy 
I just duplicated the issue on our repo so we can track what happens and warn others in case someone faces the same issue.

We'll reply here if it seems to be something from snapcraft.io's side :smile:

**Comment by jkfran** [comment]
Hi @JackDandy ,

We have a long queue for builds in those architectures right now. The queue seems to be caused by scheduled hardware maintenance in Launchpad.

I can see that right now you are still on queue for the arm64 and armhf architectures.

You can always check the status of our builders here:
https://launchpad.net/builders

As you can see there is a banner about the maintenance announcement, he is the link to the announcement:
https://lists.ubuntu.com/archives/launchpad-announce/2020-November/000107.html

Thank you!

**Comment by JackDandy** [comment]
Things have returned to normal, thanks guys 👍
